DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS name;

CREATE TABLE image(
	studentID INTEGER PRIMARY KEY,
	imageId VARCHAR(200) NOT NULL
);

CREATE TABLE name(
	studentID INTEGER AUTO INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	firstname VARCHAR(50) NOT NULL
);
